### PR TITLE
xmlunit-legacy: Simplify Diff#usesUnknownElementQualifier implementat…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…ion.

ElementNameAndTextQualifier and ElementNameAndAttributeQualifier extend ElementNameQualifier, so remove unreachable code.

### CODE REVIEW

**Comment by bodewig** [comment]
Hmm, technically you are correct but I think you are pointing at a bug.

I need to revisit the code and my line of thinking (it's been more than nine years since I've written the code :-). To me it looks as if the purpose here was to identify cases where people use an `ElementQualifier` that we cannot directly map to an `ElementSelector`. So `instanceof` would just be wrong for non-final classes. Also I'm not really sure why `compareUnmatched` unconditionally triggers `NewDifferenceEngine` - https://github.com/xmlunit/xmlunit/commit/8de1a42f32f117a2fe05c410e6bbfcc700b404ee looks dubious.

**Comment by PascalSchumacher** [comment]
I guess you are right ( I lack the necessary knowlegde of xmlunit to be sure).

I created this pull request after looking at the results of static code analysis provided byt lgtm.com (see: https://lgtm.com/projects/g/xmlunit/xmlunit).

**Comment by bodewig** [comment]
Actually `NewDifferenceEngine` contains an adapter from `ElementQualifier` to `ElementSelector` that is supposed to work regardless, so I've simply removed the check and thus the code that lgtm.com didn't like.

**Comment by PascalSchumacher** [comment]
Thanks! 👍

**Pull request closed without merging**
