### PR TITLE
Add TypeMatcher in xmlunit-matchers

### PR DESCRIPTION
**Pull request by krystiankaluzny**
TypeMatcher allows to check if an examined string value can be converted to specified type and perform matching on the converted value.
For now 4 types are support: BigDecimal, Double, Integer and Boolean
This feature is response on #133 and works well with `EvaluateXPathMatcher`:
```java
assertThat(xml, hasXPath("count(//fruits/fruit)", asBigDecimal(is(greaterThan(BigDecimal.ONE)))));
```

### CODE REVIEW

**Comment by krystiankaluzny** [comment]
Using 1/0 as true/false is natural in C/C++ or, at least it was, when I used those languages few years ago.
So it was natural for me to treat 0/1 as boleans.
If you think it is confusing, we can remove it now and if users need this feature, we will simply add it.

**Comment by phbenisc** [comment]
You might also consider following information: In XML Schema 1.0 a boolean can be one of these: true, false, 1 or 0. See https://www.w3.org/TR/xmlschema-2/#boolean  . In XML Schema 1.1 this Issue is "fixed" https://www.w3.org/TR/xmlschema11-2/#boolean

I also believe prior to SOAP 1.2 XML Schema 1.0 is used. Quite a few SOAP-Services should accept 1 and 0 as valid boolean values. So you could argue that it still is quite common. I personally think 1/0 is nowadays a bad practice and should be avoided.

**Comment by krystiankaluzny** [comment]
Ok, to be consistent I also removed 0/1 to boolean conversion from assertj module

**Comment by bodewig** [comment]
we may want to note this as a breaking change inside the AsserJ module.

**Pull request merged**
