### PR TITLE
Issue 232 diff tostring refactoring

### PR DESCRIPTION
**Pull request by Boiarshinov**
Related to [Issue 232](https://github.com/xmlunit/xmlunit/issues/232)

Change the behavior of `Diff.toString()` method - return string representations of all failed comparisons insted of only first one.
Also fixed some typos.

Sorry for not adding any tests. I have looked to `DiffBuilderTest` and didn't found any test which would assert fail message. All of them just checked the difference existance.

### CODE REVIEW

**Comment by Boiarshinov** [comment]
CI fails only on openJDK 14 with failing on request to maven central:
> Transfer failed for https://maven-central.storage-download.googleapis.com/maven2/org/apache/apache/13/apache-13.pom 503 Service Unavailable

@bodewig Sorry, I don't have permissions to rebuild PR on Travis. Could you rerun it?

**Comment by bodewig** [comment]
Thank you @Boiarshinov - apart from my comment over at #232: please don't make any additional unrelated changes "while you are it". I prefer a separate PR for typo fixes or cosmetic changes. This allows the real change to be reviewed more easily.

**Comment by Boiarshinov** [comment]
@bodewig I've moved cosmetic changes to separate PR: https://github.com/xmlunit/xmlunit/pull/234

**Comment by Boiarshinov** [comment]
I close this PR cause of that discussion: https://github.com/xmlunit/xmlunit/issues/232#issuecomment-933179823

**Pull request closed without merging**
