### PR TITLE
Port to hamcrest 2.1

### PR DESCRIPTION
**Pull request by terminus-brut**

### CODE REVIEW

**Comment by bodewig** [comment]
Thank you @terminus-brut !

After this change the matchers would no longer work with Hamcrest 1.x, is that correct?

If so I'd probably rather add an additional `xmlunit-matchers2` or so project that was tied to Hamcrest 2.x rather than breaking things who don't see any pressing need to upgrade Hamcrest.

On a related note, do the current matchers not work for Hamcrest 2.x? If they do, why would we want to upgrade the dependency?

**Comment by terminus-brut** [comment]
Hi, I am not sure if you will want to accept this, but in case you will, the PR should be correct.
I am maintaining some Fedora packages (including xmlunit) with the latest version of hamcrest and I ported about 3 packages this way.
According to this: https://github.com/hamcrest/JavaHamcrest/blob/master/CHANGES.md#breaking-changes-for-21

But you are right, there is probably no need to update if you don't need to.

**Comment by bodewig** [comment]
I think here is a difference between an application and a library.

As a library the dependency we specify will set a lower bound for the version our users can use themselves - Maven exclusions and similar tricks ignored. They are free to pick newer ones. Therefore I tend to not update dependencies unless there is a good reason to, as this allows our users more freedom of choice.

Judging from the code changes you've made - dropping an annotation - I'd expect the existing matchers to work with Hamcrest 2.1 as they are. In that case I'd rather not update.

Many thanks for your PR, though. And many thanks for maintaining he Fedora package for us :-)

**Comment by bodewig** [comment]
I've added a small maven project with commit 9e237e8 that runs xmlaunit-matcher's own unit tests with Hamcrest 2.2 and it seems to work. Therefore I don't see a reason to upgrade the dependency immediately.

I'll need to add running the test to the travis pipeline, but will have to fix that first, I'm afraid.

**Pull request closed without merging**
