### PR TITLE
initial placeholder

### PR DESCRIPTION
**Pull request by zheng-wang**

### CODE REVIEW

**Comment by bodewig** [comment]
Many thanks!

I'm deliberately not using author tags, would it be OK with you if I removed the "Created by" lines? You will certainly be credited in the release notes.

**Comment by zheng-wang** [comment]
No problem. I have removed the author tags which were created by my IDE template.

**Comment by bodewig** [comment]
It would be good to add something to the [user guide](https://github.com/xmlunit/user-guide/wiki), I'll try to find some time to start this.

Many thanks again.

**Comment by bodewig** [comment]
I've just published 2.5.1-SNAPSHOT jars of the new module and updated the public javadocs at www.xmlunit.org

**Comment by zheng-wang** [comment]
Cool, thanks.

**Comment by bodewig** [comment]
I've reworked `PlaceholderDifferenceEvaluator` so it now also works for attributes and added infrastructure that should allow new placeholder keywords to become supported more easily. It would be good if you could take a look to ensure I've been moving into the direction you wanted it to go.

**Comment by zheng-wang** [comment]
Great job Stefen! Now the code is less prototyped and more frameworkized. The separation of concerns (placeholder specific logic goes to different classes) is a must go path I believe.

The complexity of the code increased a little bit but I can't think of a simpler way to achieve the separation of concerns. Eventually it should not be a problem to me as the main direction I have is requirement (from API user's perspective) which is reflected in the unit tests. : )

**Comment by bodewig** [comment]
OK, thanks.

I think I may have gone a bit too far and thus the API may be too limited. Right now the keyword between `${xmlunit.` and `}` has to be a constant. I can easily envision something like `${xmlunit.matches(some-regex)}` which would require to expand the placeholder language.

But we can fix that once we get there :-)

**Pull request merged**
